apiVersion: v1
kind: Namespace
metadata:
  name: dotnet-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dotnet-app-sa
  namespace: dotnet-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace: dotnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: dotnet-app-sa
      containers:
      - name: myapp-container
        image: docker.io/shubhampawar819/dotnet-app:latest
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 15
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-service
  namespace: dotnet-app
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
    nodePort: 31111

