name: CI
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: dotnet-app
      TAG: ${{ github.sha }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Docker build and add tag
        run: docker build -t shubhampawar819/$IMAGE_NAME:$TAG -f Dockerfile .

      - name: Docker Registry login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to docker registry
        run: docker push shubhampawar819/$IMAGE_NAME:$TAG

      - name: Print success message!
        run: echo "Image pushed successfully with name shubhampawar819/$IMAGE_NAME:$TAG"
